name: Autocomment atime-based performance regression analysis on PRs

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  comment:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: safe-dir-check
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global --add safe.directory '*'

    - name: Manage refs
      run: |
        git switch "${GITHUB_BASE_REF}"
        git switch "${GITHUB_HEAD_REF}"
        git for-each-ref --format="%(refname)" | while read ref; do
          git show-ref --quiet --verify $ref 2>/dev/null || git update-ref -d $ref
        done
      shell: bash

    - name: R Setup
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Set up the required system dependency libgit2
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libgit2-dev

    - name: Install atime and initiate magic
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}    
      run: |
        R -e '
          r = getOption("repos");
          r["CRAN"] = "http://cran.us.r-project.org";
          options(repos = r);
          start_installation <- Sys.time();
          install.packages("atime", dependencies = TRUE); 
          finish_installation_start_running_tests <- Sys.time();
          atime::atime_pkg(Sys.getenv("GITHUB_WORKSPACE"));
          finish_running_tests <- Sys.time();
          installation_time <- as.numeric(difftime(finish_installation_start_running_tests, start_installation, units = "secs"));
          tests_time <- as.numeric(difftime(finish_running_tests, finish_installation_start_running_tests, units = "secs"));
          cat("ATIME_INSTALL_RUNTIME=", installation_time, "\\n", file="/dev/stderr");
          cat("ATIME_PKG_RUNTIME=", tests_time, "\\n", file="/dev/stderr");
             '
        echo "ATIME_INSTALL_RUNTIME=${installation_time}" >> $GITHUB_ENV
        echo "ATIME_TESTS_RUNTIME=${tests_time}" >> $GITHUB_ENV
      shell: bash

    - name: Upload results
      id: artifact-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: atime-results
        path: inst/atime/

    - name: Push generated plot along with relevant information on the PR thread as a GH-bot comment
      run: |
        echo "![Comparison Plot](./inst/atime/tests_all_facet.png)" >> report.md
        echo -e "\nGenerated via commit ${{ github.event.pull_request.head.sha }}" >> report.md
        echo -e "\nDownload link for the artifact containing the test results: [↓ atime-results.zip](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }})" >> report.md
        echo -e "\nTime taken to install \`atime\`: $((ATIME_INSTALL_RUNTIME%3600/60)) minutes and $((ATIME_INSTALL_RUNTIME%60)) seconds" >> report.md
        echo -e "\nTime taken to run \`atime::atime_pkg\` on the tests: $((ATIME_TESTS_RUNTIME%3600/60)) minutes and $((ATIME_TESTS_RUNTIME%60)) seconds" >> report.md
        cml comment update report.md
      shell: bash
