on:
  push:
    branches:
     - master
     - 1-15-99
  pull_request:
    branches:
     - master
     - 1-15-99

name: lint

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            r-lib/lintr
            local::.
          needs: lint

      - name: Lint
        run: |
          if (file.exists(f <- ".ci/.lintr.R")) message("Found config file, with contents:\n", readChar(f, file.size(f))) else stop("Config file not found! Here's where we are: ", getwd(), "\nHere's what I see:\n", paste(list.files(all = TRUE, recursive = TRUE), collapse = "\n"))
          # TODO(r-lib/lintr#2512): use 'env' instead
          options(lintr.linter_file = ".ci/.lintr")
          lintr::lint_package()
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
